kind: Deployment
apiVersion: apps/v1
metadata:
  name: sentry-operator
  namespace: sentry
  labels:
    app: sentry-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentry-operator
  template:
    metadata:
      name: sentry-operator
      labels:
        app: sentry-operator
    spec:
      containers:
        - name: sentry-operator
          image: kanadaj/sentry-operator:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ASPNETCORE_URLS
              value: http://+:5000
          ports:
            - name: http
              containerPort: 5000
      restartPolicy: Always
      serviceAccountName: sentry-operator
---
apiVersion: v1
kind: Service
metadata:
  name: sentry-operator
  labels:
    app: sentry-operator
spec:
    ports:
      - name: http
        port: 5000
        targetPort: 5000
    selector:
        app: sentry-operator
    type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
  - apiGroups:
      - sentry.io
      - coordination.k8s.io
    resources:
      - sentrydeployments
      - leases
    verbs:
      - '*'
  - apiGroups:
      - ""
      - apps
    resources:
      - pods
      - deployments
      - services
      - secrets
      - configmaps
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
      - list
      - update
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs:
      - create
      - get
      - patch
      - update
      - delete
  - apiGroups:
      - sentry.io
    resources:
      - sentrydeployments/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - pods/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - services/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - cert-manager.io
    nonResourceURLs: []
    resources:
      - certificates
    verbs:
      - create
      - get
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sentry-operator
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: sentry-operator
subjects:
    - kind: ServiceAccount
      name: sentry-operator
      namespace: sentry
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sentrydeployments.sentry.io
spec:
  group: sentry.io
  names:
    kind: SentryDeployment
    listKind: SentryDeploymentList
    plural: sentrydeployments
    singular: sentrydeployment
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            status:
              description: Status object for the entity.
              properties:
                status:
                  type: string
                message:
                  nullable: true
                  type: string
                lastVersion:
                  nullable: true
                  type: string
              type: object
            spec:
              description: Specification of the kubernetes object.
              properties:
                version:
                  description: The version of sentry to use; defaults to 23.6.1. Make sure to either use a version tag or 'nightly'
                  nullable: true
                  type: string
                dockerComposeUrl:
                  description: The URL of the docker-compose.yml file; if specified we will use the version for the images but the docker-compose for the container architecture
                  nullable: true
                  type: string
                config:
                  description: The config for the Sentry deployment
                  nullable: true
                  properties:
                    eventRetentionDays:
                      description: The amount of days to keep events for
                      format: int32
                      type: integer
                    bind:
                      description: You can either use a port number or an IP:PORT combo for SENTRY_BIND
                      type: string
                    image:
                      description: The image to use for Sentry
                      nullable: true
                      type: string
                    snubaImage:
                      description: The image to use for Snuba
                      nullable: true
                      type: string
                    relayImage:
                      description: The image to use for Relay
                      nullable: true
                      type: string
                    symbolicatorImage:
                      description: The image to use for Symbolicator
                      nullable: true
                      type: string
                    vroomImage:
                      description: The image to use for Vroom
                      nullable: true
                      type: string
                    wal2JsonVersion:
                      description: The version of Wal2Json to use
                      type: string
                    healthCheckInterval:
                      description: The interval to use for health checks
                      type: string
                    healthCheckTimeout:
                      description: The timeout to use for health checks
                      type: string
                    healthCheckRetries:
                      description: The amount of retries to use for health checks
                      type: string
                    postgres:
                      description: The config for the Postgres database
                      nullable: true
                      properties:
                        engine:
                          nullable: true
                          type: string
                        name:
                          nullable: true
                          type: string
                        user:
                          nullable: true
                          type: string
                        password:
                          nullable: true
                          type: string
                        host:
                          nullable: true
                          type: string
                        port:
                          nullable: true
                          type: string
                      type: object
                    redis:
                      description: The config for redis
                      items:
                        properties:
                          host:
                            nullable: true
                            type: string
                          password:
                            nullable: true
                            type: string
                          port:
                            nullable: true
                            type: string
                          database:
                            nullable: true
                            type: string
                        type: object
                      nullable: true
                      type: array
                    additionalFeatureFlags:
                      description: Additional feature flags to enable
                      items:
                        type: string
                      nullable: true
                      type: array
                    additionalPythonPackages:
                      description: Additional Python packages to install
                      items:
                        type: string
                      nullable: true
                      type: array
                    mail:
                      description: The config for mail
                      nullable: true
                      properties:
                        host:
                          type: string
                        port:
                          format: int32
                          type: integer
                        username:
                          type: string
                        password:
                          type: string
                        useTLS:
                          type: boolean
                        useSSL:
                          type: boolean
                        from:
                          nullable: true
                          type: string
                        mailgunApiKey:
                          nullable: true
                          type: string
                      type: object
                  type: object
                replicas:
                  description: Override each container's number of replicas here by name
                  nullable: true
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                environment:
                  description: Override environmental variables here; this is applied to all containers with matching env vars
                  nullable: true
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                resources:
                  description: Override the default resource limits
                  nullable: true
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                certificate:
                  nullable: true
                  properties:
                    install:
                      nullable: true
                      type: boolean
                    certificateCRDName:
                      description: Override the name of the Certificate CRD generated
                      nullable: true
                      type: string
                    issuerName:
                      description: Override the name of the issuer
                      nullable: true
                      type: string
                    issuerKind:
                      description: Override the kind of the issuer
                      type: string
                    secretName:
                      description: Override the name of the certificate secret
                      nullable: true
                      type: string
                    customHosts:
                      description: Add additional hosts to the certificate
                      items:
                        type: string
                      type: array
                  type: object
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}