apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sentrydeployments.sentry.io
spec:
  group: sentry.io
  names:
    kind: SentryDeployment
    listKind: SentryDeploymentList
    plural: sentrydeployments
    singular: sentrydeployment
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          status:
            description: Status object for the entity.
            properties:
              status:
                type: string
            type: object
          spec:
            description: Specification of the kubernetes object.
            properties:
              version:
                description: The version of sentry to use; defaults to 23.6.1. Make sure to either use a version tag or 'nightly'
                nullable: true
                type: string
              dockerComposeUrl:
                description: The URL of the docker-compose.yml file; if specified we will use the version for the images but the docker-compose for the container architecture
                nullable: true
                type: string
              config:
                description: The config for the Sentry deployment
                nullable: true
                properties:
                  eventRetentionDays:
                    description: The amount of days to keep events for
                    format: int32
                    type: integer
                  bind:
                    description: You can either use a port number or an IP:PORT combo for SENTRY_BIND
                    type: string
                  image:
                    description: The image to use for Sentry
                    type: string
                  snubaImage:
                    description: The image to use for Snuba
                    type: string
                  relayImage:
                    description: The image to use for Relay
                    type: string
                  symbolicatorImage:
                    description: The image to use for Symbolicator
                    type: string
                  vroomImage:
                    description: The image to use for Vroom
                    type: string
                  wal2JsonVersion:
                    description: The version of Wal2Json to use
                    type: string
                  healthCheckInterval:
                    description: The interval to use for health checks
                    type: string
                  healthCheckTimeout:
                    description: The timeout to use for health checks
                    type: string
                  healthCheckRetries:
                    description: The amount of retries to use for health checks
                    type: string
                type: object
              replicas:
                description: Override each container's number of replicas here by name
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              environment:
                description: Override environmental variables here; this is applied to all containers with matching env vars
                nullable: true
                type: object
                x-kubernetes-preserve-unknown-fields: true
              resources:
                description: Override the default resource limits
                nullable: true
                properties:
                  web:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  worker:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  cron:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  snuba:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  relay:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  consumer:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  ingest:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  forwarder:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  replacer:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                  geoIP:
                    nullable: true
                    properties:
                      claims:
                        items:
                          properties:
                            name:
                              type: string
                          type: object
                        type: array
                      limits:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                      requests:
                        type: object
                        x-kubernetes-preserve-unknown-fields: true
                    type: object
                type: object
              certSecretName:
                description: Override the name of the certificate secret
                nullable: true
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}