apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator-role
rules:
- apiGroups:
  - sentry.io
  - coordination.k8s.io
  resources:
  - sentrydeployments
  - leases
  verbs:
  - '*'
- apiGroups:
  - apps
  - ""
  resources:
  - deployments
  - secrets
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - update
- apiGroups:
  - ""
  - admissionregistration.k8s.io
  resources:
  - services
  - validatingwebhookconfigurations
  - mutatingwebhookconfigurations
  verbs:
  - create
  - get
  - patch
  - update
  - delete
- apiGroups:
  - sentry.io
  resources:
  - sentrydeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - services/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cert-manager.io
  nonResourceURLs: []
  resources:
  - certificates
  verbs:
  - create
  - get
  - patch
  - delete