apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsVENDQVR1Z0F3SUJBZ0lJRVZkUUZVWWMybWd3Q2dZSUtvWkl6ajBFQXdRd1BqRVRNQkVHQTFVRUJ4TUsKUzNWaVpYSnVaWFJsY3pFTU1Bb0dBMVVFQmhNRFJFVldNUmt3RndZRFZRUURFeEJQY0dWeVlYUnZjaUJTYjI5MApJRU5CTUI0WERUSTJNRGN4TURBd01EQXdNRm9YRFRNeE1EY3hNREF3TURBd01Gb3dQakVUTUJFR0ExVUVCeE1LClMzVmlaWEp1WlhSbGN6RU1NQW9HQTFVRUJoTURSRVZXTVJrd0Z3WURWUVFERXhCUGNHVnlZWFJ2Y2lCU2IyOTAKSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRVRCS1V4R1M3TWV0MHZmTDZxN1gzU1p1SwpiRm56N1JUcHBJR25tQ3kwR2hMMDdaZmpWYUV0dnNGNXE5b0REc0d4ODVhWE9GRDNVTnA3R1lzaVdSRldGS01qCk1DRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVNZd0NnWUlLb1pJemowRUF3UUQKU0FBd1JRSWhBTVVOYVd0cmxyTFUwS0lYemhXSExVeWF6eUR0TUNPaTJBekRRQkptVWNDMkFpQkE1TEZBZnJWKwpRT0dQWmR2ejV4eWFTVFp6clhRb0IrZWFKYTgydjhxaEFRPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: operator
      path: /validate/sentrydeployment
  matchPolicy: Exact
  name: validate.sentrydeployment.sentry.io.v1
  rules:
  - apiGroups:
    - sentry.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - sentrydeployments
  sideEffects: None