apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validators
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJsVENDQVR1Z0F3SUJBZ0lJZTBBL0FVNGxQbGN3Q2dZSUtvWkl6ajBFQXdRd1BqRVRNQkVHQTFVRUJ4TUsKUzNWaVpYSnVaWFJsY3pFTU1Bb0dBMVVFQmhNRFJFVldNUmt3RndZRFZRUURFeEJQY0dWeVlYUnZjaUJTYjI5MApJRU5CTUI0WERUSTJNRGN4TXpBd01EQXdNRm9YRFRNeE1EY3hNekF3TURBd01Gb3dQakVUTUJFR0ExVUVCeE1LClMzVmlaWEp1WlhSbGN6RU1NQW9HQTFVRUJoTURSRVZXTVJrd0Z3WURWUVFERXhCUGNHVnlZWFJ2Y2lCU2IyOTAKSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJS29aSXpqMERBUWNEUWdBRWppK3RaWmVLMHBWQXo1NWgxeVh4N0t6UQpmbXdlcXJheGJ4Z0w0RGpoSVNYQmF0OGdhT0oxbHpCdjZncGJkMzBURWE4R3BFZkNQanNDaEpxVlNnaHkxNk1qCk1DRXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU9CZ05WSFE4QkFmOEVCQU1DQVNZd0NnWUlLb1pJemowRUF3UUQKU0FBd1JRSWdJOEwxSWg3VU1TR3lSVmJRSndqaVM0VERKVmowU0IweDV0WjVWV2NEbnlNQ0lRRGwvN3JlTVF1aApZN0c1UDhzd1QwY09JSjE1R1JJOTdzdVJhdUhEcDNQZ3JBPT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQ==
    service:
      name: operator
      path: /validate/sentrydeployment
  matchPolicy: Exact
  name: validate.sentrydeployment.sentry.io.v1
  rules:
  - apiGroups:
    - sentry.io
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - sentrydeployments
  sideEffects: None